Add accessibility statement and link to statement
alphagov/govuk-account-tech-docs pull request #3
Opened 2021-01-11 15:56 UTC by jonathanglassman

Add accessibility statement and link to statement to tech docs as per https://trello.com/c/z3P1iW1H/547-accessibility-statements-and-fixes-for-team-manual-and-tech-docs

2021-01-13 15:45 UTC, huwd approved these changes

2021-01-13 15:46 UTC, huwd requested changes
These could be squashed down into a single commit I think

2021-01-14 09:25 UTC, jonathanglassman commented
@huwd squashed, can you approve again please?

2021-01-14 10:53 UTC, huwd approved these changes

2021-01-14 10:56 UTC, merged